### ISSUE TITLE
Polygon label is not showing

### ISSUE THREAD

**Issue by iqnaul** [DataVizForAll/leaflet-maps-with-google-sheets#106]
Hi, I succeeded to add polygon from my own data. I can make sure that the column name is correct, but the label is not showing up.

Any suggestions?
Thanks

**Comment by ilyankou** [comment]
Hey @iqnaul:

It would be helpful if you shared your Google sheet + geoJSON for me to look at.

Right now I can only recommend you make sure the column name is *really* correct (eg capitalization, no trailing spaces, etc), and your `Show Polygon Labels at Zoom Level` is set up to a meaningful number (ie between ~6 and 16).

**Comment by iqnaul** [comment]
Hi @ilyankou 

This is my polygon GeoJSON data in zip file and the field name to be displayed as label is "DESA" all caps
this is the link of my Google Sheet config [https://docs.google.com/spreadsheets/d/1rjk03oVO1KwqgMDje9YTdH5GKEBfVkcMG3xciRJpHOk/edit#gid=0]

Thanks for your help

**Comment by ilyankou** [comment]
@iqnaul please share the same link to the Sheets that you put in your `google-doc-url.js` file.

**Comment by iqnaul** [comment]
@ilyankou yes that is the correct URL in my Sheets as mentioned in my previous comment https://docs.google.com/spreadsheets/d/1rjk03oVO1KwqgMDje9YTdH5GKEBfVkcMG3xciRJpHOk/edit#gid=0

**Comment by ilyankou** [comment]
@iqnaul 

OK, so the issue is, when the script tries to calculate the coordinates for the Label, it uses a set of coordinates defining the Polygon. Your GeoJSON contains a collection of `MultiPolygon`s, not `Polygon`s, meaning that your coordinates lie one level deeper in the array.

Either try to convert your GeoJSON to a collection of Polygons, or in `script.js` find the piece

```javascript
polylabel(layer.feature.geometry.coordinates, 1.0).reverse()
```

and change it to

```javascript
polylabel(layer.feature.geometry.coordinates[0], 1.0).reverse()
```

This *might* help but I don't know for sure.

**Comment by iqnaul** [comment]
Hi @ilyankou 
I finally convert the multipolygons into single-polygon using QGIS, and now the label is showing.

thank you for your help!
